CREATE TABLE tb_com_x (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    current_avg_ext DOUBLE,
    frequency_ext DOUBLE,
    apparent_power_a_ext DOUBLE,
    active_power_a_ext DOUBLE,
    reactive_power_a_ext DOUBLE,
    power_factor_a_ext DOUBLE,
    voltage_ab_ext DOUBLE,
    voltage_an_ext DOUBLE,
    current_a_ext DOUBLE,
    apparent_power_b_ext DOUBLE,
    active_power_b_ext DOUBLE,
    reactive_power_b_ext DOUBLE,
    power_factor_b_ext DOUBLE,
    voltage_bc_ext DOUBLE,
    voltage_bn_ext DOUBLE,
    current_b_ext DOUBLE,
    apparent_power_c_ext DOUBLE,
    active_power_c_ext DOUBLE,
    reactive_power_c_ext DOUBLE,
    power_factor_c_ext DOUBLE,
    voltage_ca_ext DOUBLE,
    voltage_cn_ext DOUBLE,
    current_c_ext DOUBLE,
    fwdVAh_ext DOUBLE,
    fwdWh_ext DOUBLE,
    fwdVARh_ind_ext DOUBLE,
    fwdVARh_cap_ext DOUBLE,
    revVAh_ext DOUBLE,
    revWh_ext DOUBLE,
    revVARh_ind_ext DOUBLE,
    revVARh_cap_ext DOUBLE,
    present_demand_ext DOUBLE,
    rising_demand_ext DOUBLE NULL
);
